---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/BloodVessels/BloodVessels.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/152392/articles/166121/master/file/figures/BloodVessels/BloodVessels.png"
